version: "3.7"
services:
  postgres-db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres-db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres-db:pgsql-server
  backend:
    image: hailey-and-weiwei-backend:latest
    build:
      context: ../backend
      dockerfile: Containerfile
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8081:8081
volumes:
  db-data:
  pgadmin-data:
