version: "3.7"
services:
  postgres-db:
    image: postgres:13.2-alpine
    container_name: hailey-and-weiwei-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=hailey_and_weiwei
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: hailey-and-weiwei-postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hailey-and-weiwei-pgadmin
    depends_on:
      - postgres-db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=hailey_and_weiwei
    ports:
      - ${PGADMIN_PORT:-8080}:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres-db:pgsql-server
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: hailey-and-weiwei-pgadmin

  backend:
    image: ghcr.io/the3dsandwich/hailey-and-weiwei-backend:dev
    container_name: hailey-and-weiwei-backend
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres-db:5432/postgres}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      RESEND_API_KEY: ${RESEND_API_KEY:-changeme}
      ALLOW_ORIGIN: ${ALLOW_ORIGIN:-https://haileyandweiweiwedding.the3dsandwich.com}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=hailey_and_weiwei
    ports:
      - ${BACKEND_PORT:-8081}:8081
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: hailey-and-weiwei-backend

  frontend:
    image: ghcr.io/the3dsandwich/hailey-and-weiwei-frontend:dev
    container_name: hailey-and-weiwei-frontend
    depends_on:
      - backend
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=hailey_and_weiwei
    ports:
      - ${FRONTEND_PORT:-8082}:3000
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: hailey-and-weiwei-frontend

  watchtower:
    image: containrrr/watchtower
    container_name: hailey-and-weiwei-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 * * ? * *
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_SCOPE=hailey_and_weiwei
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: hailey-and-weiwei-watchtower

volumes:
  postgres-db-data:
  pgadmin-data:
