/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6hGCar6KFrQ
 */
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";

export const GuestDetailTable = (data: {
  dataList: [
    {
      name?: string;
      phone?: string;
      email?: string;
      comments?: string;
      tags?: [string];
    }
  ];
}) => {
  const { dataList } = data;

  return (
    <Table key="1">
      <TableHeader>
        <TableRow className="text-xs font-medium tracking-wide uppercase">
          <TableHead className="w-1/4">Name</TableHead>
          <TableHead>Email</TableHead>
          <TableHead>Phone</TableHead>
          <TableHead>Tags</TableHead>
          <TableHead></TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {dataList.length > 0 &&
          dataList?.map((d) => (
            <GuestDetailTableRow
              name={d.name}
              phone={d.phone}
              email={d.email}
              comments={d.comments}
              tags={d.tags}
              key={d.name}
            />
          ))}
      </TableBody>
    </Table>
  );
};

const GuestDetailTableRow = (data: {
  name?: string;
  phone?: string;
  email?: string;
  comments?: string;
  tags?: [string];
}) => {
  const { name, phone, email, comments, tags } = data;
  return (
    <TableRow className="hover:bg-gray-100 dark:hover:bg-gray-800">
      <TableCell className="font-semibold">{name}</TableCell>
      <TableCell>{email}</TableCell>
      <TableCell>{phone}</TableCell>
      <TableCell className="space-x-2">
        {tags?.map((t) => (
          <Badge variant="outline" key={t}>
            {t}
          </Badge>
        ))}
      </TableCell>
      <TableCell className="w-1/12 text-right">
        <Popover>
          <PopoverTrigger asChild>
            <Button size="icon" variant="ghost">
              <ChevronDownIcon className="h-4 w-4" />
              <span className="sr-only">View</span>
            </Button>
          </PopoverTrigger>
          <PopoverContent>
            <p>{comments}</p>
          </PopoverContent>
        </Popover>
      </TableCell>
    </TableRow>
  );
};

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}
