name: Deploy Images to GHCR

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  packages: write

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: "Build Image"
        run: |
          docker build . -f Containerfile --tag ghcr.io/${{github.actor}}/hailey-and-weiwei-backend:latest
          docker push ghcr.io/${{github.actor}}/hailey-and-weiwei-backend:latest
